apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: observatory-web
  namespace: default
  labels:
    component: observatory
spec:
  replicas: 5
  revisionHistoryLimit: 2
  minReadySeconds: 1
  selector:
    matchLabels:
      component: observatory-web
  template:
    metadata:
      labels:
        component: observatory-web
    spec:
      containers:
      - name: observatory-web
        image: underscorenygren/observatory-web:latest
        resources:
          requests:
            cpu: 100m
            memory: 10M
          limits:
            cpu: 1000m
            memory: 1000M
        env:
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: "redshift-metrics"
              key: host
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: "redshift-metrics"
              key: db
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: "redshift-metrics"
              key: user
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: "redshift-metrics"
              key: port
        - name: PG_PWD
          valueFrom:
            secretKeyRef:
              name: "redshift-metrics"
              key: password
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: "observatory-aws"
              key: "bucket"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: "observatory-aws"
              key: "id"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: "observatory-aws"
              key: "secret"

      volumes:
      - name: storage
        emptyDir: {}
