apiVersion: v1
kind: Service
metadata:
  name: observatory
  labels:
    component: observatory
spec:
  selector:
    component: observatory
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: "ClusterIP"
  clusterIP: "None"
